In [ ]:
[선형회귀]

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [4]:
W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [5]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [6]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [7]:
optimizer = optim.SGD([W, b], lr = 0.01)

In [9]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
    
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {: .3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W:  0.353, b: 0.151 Cost: 14.770963
Epoch  100/2000 W:  1.746, b: 0.577 Cost: 0.047939
Epoch  200/2000 W:  1.801, b: 0.453 Cost: 0.029624
Epoch  300/2000 W:  1.843, b: 0.356 Cost: 0.018306
Epoch  400/2000 W:  1.877, b: 0.280 Cost: 0.011312
Epoch  500/2000 W:  1.903, b: 0.220 Cost: 0.006990
Epoch  600/2000 W:  1.924, b: 0.173 Cost: 0.004319
Epoch  700/2000 W:  1.940, b: 0.136 Cost: 0.002669
Epoch  800/2000 W:  1.953, b: 0.107 Cost: 0.001649
Epoch  900/2000 W:  1.963, b: 0.084 Cost: 0.001019
Epoch 1000/2000 W:  1.971, b: 0.066 Cost: 0.000630
Epoch 1100/2000 W:  1.977, b: 0.052 Cost: 0.000389
Epoch 1200/2000 W:  1.982, b: 0.041 Cost: 0.000240
Epoch 1300/2000 W:  1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W:  1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W:  1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W:  1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W:  1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W:  1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W:  1.997, b: 

In [11]:
import torch
w = torch.tensor(2.0, requires_grad = True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    z = 2 * w
    
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [ ]:
[자동 미분]

In [38]:
import torch

In [74]:
w = torch.FloatTensor([1, 2, 3])
w.requires_grad = True
print(w.requires_grad)

True


In [75]:
y = w**2
z = 2*y + 5
print(z)

tensor([ 7., 13., 23.], grad_fn=<AddBackward0>)


In [76]:
grad=torch.Tensor([0.1, 1, 10])
z.backward(grad)
print(w.grad)

tensor([  0.4000,   8.0000, 120.0000])
